queue_rules:
  - name: hotfix
    merge_conditions:
      - and:
        - base=main
        - label!=do-not-merge
    merge_method: squash
    speculative_checks: 3
    queue_branch_prefix: mergify_poc/hotfix_queue/

  - name: default
    merge_conditions:
      - and:
        - base=main
        - label!=do-not-merge
    merge_method: squash
    speculative_checks: 3
    queue_branch_prefix: mergify_poc/merge_queue/


pull_request_rules:
  - name: Enqueue on Approval
    conditions:
      - and:
          - base=main
          - label=automerge
          - label!=stale
          - label!=do-not-merge
          - -files~=^.github/
    actions:
      queue:

  - name: Enqueue Extra protected
    conditions:
      - and:
          - base=main
          - "#approved-reviews-by>=2"
          - label=automerge
          - label!=stale
          - label!=do-not-merge
          - files~=^.github/
    actions:
      queue:

  - name: Enqueue Hotfix on Approval
    conditions:
      - and:
          - base=main
          - "#approved-reviews-by>=0"
          - label=hotfix
    actions:
      queue:
        name: hotfix

  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:

  - name: Label as Stale
    conditions:
      - updated-at<1 days ago
    actions:
      label:
        add:
          - stale

  - name: Close Stale Prs
    conditions:
      - label=stale
      - updated-at<1 days ago
    actions:
      close:
        message: >
          This Pr was closed due to a stale status of > 1 day.

  - name: Notify author on queue failure
    conditions:
      - 'check-failure=Queue: Embarked in merge train'
    actions:
      comment:
        message: >
          Hey @{{ author }}, this pull request failed to merge and has been
          dequeued from the merge train.  If you believe your PR failed in
          the merge train because of a flaky test, requeue it by commenting
          with `@mergifyio requeue`.
          More details can be found on the `Queue: Embarked in merge train`
          check-run.
