queue_rules:
  - name: hotfix
    merge_conditions:
      - and:
          - base=main
          - label!=do-not-merge
          - "#changes-requested-reviews-by=0"
    merge_method: squash
    speculative_checks: 3
    queue_branch_prefix: hotfix_queue/

  - name: default
    merge_conditions:
      - or:
          - and:
              - base=main
              - label!=do-not-merge
              - "#changes-requested-reviews-by=0"
              - "#approved-reviews-by>=1"
              - files~=^.github/
          - and:
              - base=main
              - "#changes-requested-reviews-by=0"
              - label!=do-not-merge
              - -files~=^.github/
    merge_method: squash
    speculative_checks: 3
    queue_branch_prefix: merge_queue/


pull_request_rules:
  - name: Enqueue on Approval
    conditions:
      - and:
          - base=main
          - label!=stale
          - label!=do-not-merge
          - or:
            - label=automerge
            - body~=(?m)^\[X\] Docs have been updated
    actions:
      queue:

  - name: Enqueue Hotfix on Approval
    conditions:
      - and:
          - base=main
          - label=hotfix
          - label!=do-not-merge
    actions:
      queue:
        name: hotfix

  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:

  - name: Add Team Label
    conditions:
      - files~=^.github/
    actions:
      label:
        add:
          - team:platform-dev-exp

  - name: Label as Stale (HUMAN)
    conditions:
      - updated-at<6 days ago
    actions:
      label:
        add:
          - stale

  - name: Label as Stale (BOT)
    conditions:
      - and:
          - updated-at<1 days ago
          - label=afs-deploy-bot
    actions:
      label:
        add:
          - stale

  - name: Close Stale Prs
    conditions:
      - label=stale
      - updated-at<1 days ago
    actions:
      close:
        message: >
          This Pr was closed due to a stale status.
          
  - name: merge when checkboxes are checked
    conditions:
      - body~=(?m)^\[X\] Docs have been updated
      - check-success=my favorite ci
    actions:
      queue:


  - name: Notify author on queue failure
    conditions:
      - 'check-failure=Queue: Embarked in merge train'
    actions:
      comment:
        message: >
          Hey @{{ author }}, this pull request failed to merge and has been
          dequeued from the merge train.  If you believe your PR failed in
          the merge train because of a flaky test, requeue it by commenting
          with `@mergifyio requeue`.
          More details can be found on the `Queue: Embarked in merge train`
          check-run.
